### ISSUE TITLE
Step 8: Adding data to 'Schools' & 'Timeslot' list

### ISSUE THREAD

**Issue by mrkeens** [OfficeDev/microsoft-teams-apps-classroom-dropin#17]
Error when importing "ImportingDataflows"
Flow save failed with code 'MultipleErrorsOccurred' and message 'The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: { "status": 404, "message": "Item not found\r\nclientRequestId: 5b45bab8-d62e-4ff6-b107-8d8a5b259430\r\nserviceRequestId: 0b3f920f-dd11-4195-b98d-f755c4e3d784", "error": { "message": "Item not found" }, "source": "excelonline-ase.azconn-ase.p.azurewebsites.net" };The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: { "status": 404, "message": "Item not found\r\nclientRequestId: 5b45bab8-d62e-4ff6-b107-8d8a5b259430", "error": { "message": "Item not found" }, "source": "excelonline-ase.azconn-ase.p.azurewebsites.net" }'.

**Comment by MarkHilburn** [comment]
mrkeens, were you able to resolve this error? I'm getting the same thing now and have not figured out what to do with it.

**Comment by mrkeens** [comment]
Hi Mark,

I was able to resolve the error.

When importing the new flow & receiving the error; there is a sneaky little button to click, "save as new flow"

This will allow you to fix each of the problems within the flow, then save from there.
[cid:image001.png@01D6FF84.B95527E0]

**Comment by MarkHilburn** [comment]
Thank you! I saw that yesterday and thought “I don’t want to save a flow that doesn’t work.”
